"use client";

import { useEffect, useMemo, useState, type CSSProperties, type PointerEvent } from "react";
import { useRouter } from "next/navigation";
import { platformIcons, type PlatformSlug } from "../../lib/platform-icons";
import styles from "./page.module.css";

type Item={id:string;title:string;channel_title:string;published_at:string;thumbnail:string;description:string;views:number;url:string;topic:string;metadata?:{signal?:string;momentum_score?:number}};
type Platform={name:string;slug:PlatformSlug;connected:boolean;index:number};
type Category={name:string;icon:string;keywords:string[]};
const platforms:Platform[]=[{name:"YouTube",slug:"youtube",connected:true,index:0},{name:"TikTok",slug:"tiktok",connected:false,index:1},{name:"LinkedIn",slug:"linkedin",connected:false,index:2},{name:"Reddit",slug:"reddit",connected:false,index:3},{name:"Discord",slug:"discord",connected:false,index:4},{name:"Snapchat",slug:"snapchat",connected:false,index:5},{name:"Pinterest",slug:"pinterest",connected:false,index:6},{name:"Spotify",slug:"spotify",connected:false,index:7},{name:"Twitch",slug:"twitch",connected:false,index:8},{name:"Facebook",slug:"facebook",connected:false,index:9},{name:"X",slug:"x",connected:false,index:10},{name:"Instagram",slug:"instagram",connected:false,index:11}];
const categories:Category[]=[{name:"Trending",icon:"✦",keywords:[]},{name:"AI & Tech",icon:"⌘",keywords:["ai","tech","technology","chatgpt","robot","phone","chip"]},{name:"Travel",icon:"✈",keywords:["travel","trip","flight","hotel","tour"]},{name:"Food",icon:"◒",keywords:["food","recipe","cooking","chef","restaurant"]},{name:"Gaming",icon:"⌁",keywords:["gaming","game","xbox","playstation","minecraft"]},{name:"Fitness",icon:"♧",keywords:["fitness","workout","gym","training"]},{name:"Podcasts",icon:"◉",keywords:["podcast","episode","interview"]},{name:"Lifestyle",icon:"◇",keywords:["lifestyle","daily","routine","home","life"]},{name:"Music",icon:"♫",keywords:["music","song","singer","album","concert"]},{name:"Fashion",icon:"◈",keywords:["fashion","style","outfit"]},{name:"Education",icon:"∑",keywords:["education","learn","tutorial","course","study"]},{name:"Business",icon:"▣",keywords:["business","startup","entrepreneur","company"]},{name:"Finance",icon:"₹",keywords:["finance","stock","money","invest","crypto"]},{name:"Sports",icon:"◈",keywords:["sports","football","cricket","basketball","tennis"]},{name:"Comedy",icon:"☺",keywords:["comedy","funny","joke","humor"]},{name:"Science",icon:"⚗",keywords:["science","space","physics","research"]},{name:"Automotive",icon:"⌁",keywords:["car","auto","motorcycle","bike","vehicle"]},{name:"Beauty",icon:"✧",keywords:["beauty","makeup","skincare","hair"]},{name:"Entertainment",icon:"▸",keywords:["movie","film","actor","entertainment","show"]},{name:"DIY & Home",icon:"⌂",keywords:["diy","home","garden","construction","craft"]},{name:"News",icon:"≡",keywords:["news","breaking","update"]},{name:"Pets",icon:"♡",keywords:["pet","dog","cat","animal"]}];
const nav=[["Discover","/"],["Creators","/creators"],["Brands","/brands"],["Opportunities","/opportunities"],["Community","/community"],["About","/about"]] as const;
const colors:Record<PlatformSlug,string>={youtube:"#FF0000",instagram:"#FD1D1D",tiktok:"#000000",x:"#000000",linkedin:"#0A66C2",facebook:"#1877F2",reddit:"#FF4500",discord:"#5865F2",snapchat:"#FFFC00",pinterest:"#E60023",spotify:"#1DB954",twitch:"#9146FF"};
const darkLogo=new Set<PlatformSlug>(["snapchat","spotify"]);
const fmt=(n:number)=>n>=1e9?`${(n/1e9).toFixed(1)}B`:n>=1e6?`${(n/1e6).toFixed(1)}M`:n>=1e3?`${(n/1e3).toFixed(1)}K`:n.toLocaleString();
const age=(s:string)=>{const m=Math.max(0,(Date.now()-new Date(s).getTime())/6e4);return m<60?`${Math.floor(m)} min ago`:`${Math.floor(m/60)}h ago`};
const categoryFor=(x:Item)=>{const t=`${x.topic} ${x.title} ${x.description}`.toLowerCase();return categories.find(c=>c.name!=="Trending"&&c.keywords.some(k=>t.includes(k)))?.name||"Other"};
const orbitPoint=(i:number,rx:number,ry:number)=>{const angle=-90+i*30,rad=angle*Math.PI/180;return {x:rx*Math.cos(rad),y:ry*Math.sin(rad)}};
const curvePath=(x:number,y:number)=>{const mx=x*.58,my=y*.58;return `M 0 0 Q ${mx} ${my-18} ${x} ${y}`};
function PlatformIcon({slug}:{slug:PlatformSlug}){const icon=platformIcons[slug];return <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path fill={darkLogo.has(slug)?"#080914":"#fff"} d={icon.path}/></svg>}

export default function LivingDiscoverReference(){
 const router=useRouter();const[items,setItems]=useState<Item[]>([]);const[filter,setFilter]=useState("Trending");const[q,setQ]=useState("");const[notice,setNotice]=useState("");const[loading,setLoading]=useState(true);const[pointer,setPointer]=useState({x:0,y:0});const[active,setActive]=useState<PlatformSlug|"all">("all");const[more,setMore]=useState(false);const[sensing,setSensing]=useState(false);const[incoming,setIncoming]=useState<number|null>(null);const[orbit,setOrbit]=useState({rx:330,ry:225,badge:68});
 useEffect(()=>{const load=async()=>{try{const r=await fetch("/api/discovery",{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.state||"DATA_UNAVAILABLE");setItems(Array.isArray(b.items)?b.items:[]);setNotice("")}catch(e){setNotice(e instanceof Error?e.message:"DATA_UNAVAILABLE")}finally{setLoading(false)}};void load();const id=window.setInterval(()=>void load(),60000);return()=>window.clearInterval(id)},[]);
 useEffect(()=>{const resize=()=>{const w=window.innerWidth;if(w<900)return setOrbit({rx:0,ry:0,badge:0});const rx=Math.min(350,Math.max(255,w*.39));const ry=Math.min(230,Math.max(170,rx*.68));const badge=Math.min(74,Math.max(58,rx*.19));setOrbit({rx,ry,badge})};resize();window.addEventListener("resize",resize);return()=>window.removeEventListener("resize",resize)},[]);
 useEffect(()=>{if(!notice)return;const id=window.setTimeout(()=>setNotice(""),4200);return()=>window.clearTimeout(id)},[notice]);
 const ranked=useMemo(()=>[...items].sort((a,b)=>(b.metadata?.momentum_score||0)-(a.metadata?.momentum_score||0)),[items]);
 const shown=useMemo(()=>{const base=filter==="Trending"?ranked:ranked.filter(x=>categoryFor(x)===filter);const s=q.trim().toLowerCase();return s?base.filter(x=>`${x.title} ${x.channel_title} ${x.description} ${x.topic}`.toLowerCase().includes(s)):base},[ranked,filter,q]);
 const visibleCats=more?categories:categories.slice(0,16);const go=(p:string)=>router.push(p);
 const move=(e:PointerEvent<HTMLElement>)=>{const r=e.currentTarget.getBoundingClientRect();setPointer({x:(e.clientX-r.left)/r.width-.5,y:(e.clientY-r.top)/r.height-.5})};
 const category=(name:string)=>{setFilter(name);setActive("all");setQ("");setNotice(`Discovery field tuned to ${name}.`)};
 const command=(value:string)=>{const s=value.trim();if(!s)return;const l=s.toLowerCase();const p=platforms.find(x=>l.includes(x.name.toLowerCase()));if(p){go(`/platform/${p.slug}?q=${encodeURIComponent(s)}`);return}const c=categories.find(x=>x.name.toLowerCase()===l||l.includes(x.name.toLowerCase()));if(c){category(c.name);return}if(l.includes("creator")){go(`/creators?q=${encodeURIComponent(s)}`);return}if(l.includes("brand")){go(`/brands?q=${encodeURIComponent(s)}`);return}if(l.includes("opportun")){go(`/opportunities?q=${encodeURIComponent(s)}`);return}setFilter("Trending");setQ(s);setActive("all")};
 const triggerIn=(i:number)=>{setIncoming(i);window.setTimeout(()=>setIncoming(null),1250)};const activatePlatform=(p:Platform)=>{triggerIn(p.index);setActive(p.slug);window.setTimeout(()=>go(`/platform/${p.slug}`),720)};
 return <main className={styles.rv} onPointerMove={move} onPointerLeave={()=>setPointer({x:0,y:0})}>
 <header className={styles.topbar}><button className={styles.brand} onClick={()=>go("/")}>RALL<span>IVIO</span><small>CREATORS. BRANDS. A BRIGHTER TOMORROW.</small></button><nav>{nav.map(([n,p])=><button key={p} className={p==="/"?styles.active:""} onClick={()=>go(p)}>{n}</button>)}</nav><form className={styles.topSearch} onSubmit={e=>{e.preventDefault();command(q)}}><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search creators, topics, brands, videos…"/></form><button className={styles.circle}>♧</button><button className={styles.circle}>☼</button><button className={styles.avatar}>R</button></header>
 <section className={styles.hero}><div className={styles.copy}><span className={styles.livePill}><i/> LIVE <b>THE CREATOR ECONOMY IS MOVING RIGHT NOW</b></span><h1>Discover<br/><em>A Brighter</em><br/>Tomorrow.</h1><p>Real trends. Real creators. Real brands.<br/>One ecosystem. Unlimited opportunities.</p><form className={styles.heroSearch} onSubmit={e=>{e.preventDefault();command(q)}}><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="What do you want to discover?"/><button type="submit">→</button></form><div className={styles.categories}>{visibleCats.map(c=><button key={c.name} className={filter===c.name?styles.selected:""} onClick={()=>category(c.name)}><span>{c.icon}</span>{c.name}</button>)}<button className={styles.more} onClick={()=>setMore(v=>!v)}>{more?"Less ↑":"+ More"}</button></div></div>
 <div className={styles.ecosystem}><div className={styles.referencePill}>Real Platforms. Real Signals. A Brighter Tomorrow.</div><div className={`${styles.field} ${sensing?styles.sensing:""}`} style={{transform:`perspective(1200px) rotateY(${pointer.x*-3}deg) rotateX(${pointer.y*2.5}deg)`}}>
  <svg className={styles.connectors} viewBox="-400 -280 800 560" aria-hidden="true"><defs><linearGradient id="conn" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stopColor="#a866ff" stopOpacity=".08"/><stop offset=".55" stopColor="#9e78ff" stopOpacity=".42"/><stop offset="1" stopColor="#55bfff" stopOpacity=".08"/></linearGradient></defs>{orbit.rx>0&&platforms.map(p=>{const pt=orbitPoint(p.index,orbit.rx,orbit.ry);return <path key={p.slug} className={sensing||incoming===p.index?styles.pulse:""} style={{"--delay":`${p.index*34}ms`} as CSSProperties} d={curvePath(pt.x,pt.y)} pathLength="1"/>})}</svg>
  <div className={styles.orbitEllipse} style={{width:orbit.rx*2,height:orbit.ry*2}}/><div className={`${styles.orbitEllipse} ${styles.inner}`} style={{width:orbit.rx*1.55,height:orbit.ry*1.55}}/>
  <div className={styles.globeScene}><div className={styles.globeVisual}><div className={styles.globeCore}/><svg className={styles.globeGrid} viewBox="0 0 300 300" aria-hidden="true"><g>{[-66,-44,-22,0,22,44,66].map(v=><ellipse key={`lat${v}`} cx="150" cy="150" rx="148" ry={Math.max(16,148*Math.cos(v*Math.PI/180))} transform={`rotate(${v/3} 150 150)`}/>)}{[-60,-30,0,30,60].map(v=><ellipse key={`lon${v}`} cx="150" cy="150" rx={Math.max(20,148*Math.abs(Math.cos(v*Math.PI/180)))} ry="148" transform={`rotate(${v} 150 150)`}/>)}</g>{Array.from({length:34},(_,i)=><circle key={i} cx={35+(i*71)%230} cy={42+(i*47)%215} r={i%5===0?2:1}/>)}</svg><div className={styles.globeRim}/></div><div className={`${styles.orbit3d} ${styles.orbitA}`}/><div className={`${styles.orbit3d} ${styles.orbitB}`}/><div className={`${styles.orbit3d} ${styles.orbitC}`}/></div>
  <div className={styles.coreText} onPointerDown={()=>setSensing(true)} onPointerUp={()=>setSensing(false)} onPointerCancel={()=>setSensing(false)} onPointerLeave={()=>setSensing(false)} onClick={()=>{setActive("all");setFilter("Trending");setQ("")}}><strong>RALL<span>IVIO</span></strong><small>CREATORS. BRANDS. PEOPLE. OPPORTUNITIES.</small><em><i/> {loading?"Syncing verified signals":`${ranked.length} verified signals`} · {active==="all"?"all sources":platforms.find(p=>p.slug===active)?.name}</em></div>
  {platforms.map(p=>{const pt=orbitPoint(p.index,orbit.rx,orbit.ry);return <button key={p.slug} className={`${styles.platform} ${p.connected?styles.connected:""} ${active===p.slug?styles.selected:""} ${incoming===p.index?styles.incoming:""}`} style={{left:`calc(50% + ${pt.x}px)`,top:`calc(50% + ${pt.y}px)`,"--brand":colors[p.slug],"--badge":`${orbit.badge||64}px`,"--delay":`${p.index*30}ms`} as CSSProperties} onClick={()=>activatePlatform(p)} onPointerEnter={()=>setActive(p.slug)}><span className={`${styles.platformIcon} ${darkLogo.has(p.slug)?styles.darkLogo:""}`}><PlatformIcon slug={p.slug}/></span><b>{p.name}</b><small>{p.connected?<><i/> Connected</>:"Explore"}</small></button>})}
 </div><div className={styles.fieldWords}><span>Explore</span><span>Connect</span><span>Create</span><span>Grow</span><b/></div></div></section>
 <section className={styles.signals}><div className={styles.signalsHead}><div><span>⚡ LIVE SIGNALS</span><h2>What is moving right now?</h2><p>Real-time trends from verified sources across the ecosystem.</p></div><div className={styles.source}><i/> YouTube Connected <small>Last updated: live · {ranked.length} observations</small></div><button onClick={()=>setNotice("Full signal view will use the same verified discovery pool.")}>View All →</button></div><div className={styles.signalRow}>{shown.slice(0,6).map(x=><button className={styles.signal} key={x.id} onClick={()=>go(`/platform/youtube?video=${encodeURIComponent(x.id)}`)}><div className={styles.thumb}><img src={x.thumbnail} alt=""/><span>▶</span></div><div className={styles.signalInfo}><small>{age(x.published_at)}</small><strong>{x.title}</strong><span>{x.channel_title}</span><em>{categoryFor(x)}</em><b>{fmt(x.views)} views</b></div></button>)}{!loading&&!shown.length&&<div className={styles.empty}>No verified observations match this field yet.</div>}{loading&&<div className={styles.empty}>Syncing verified observations…</div>}</div></section>
 {notice&&<div className={styles.toast}>{notice}</div>}<footer><strong>RALL<span>IVIO</span></strong><small>Discover what is moving. Follow the signal. Create what comes next.</small></footer></main>
}
