create table if not exists public.youtube_discovery_pool (
  id text primary key,
  title text not null,
  channel_title text not null,
  channel_id text not null,
  published_at timestamptz not null,
  thumbnail text not null,
  description text not null default '',
  views bigint not null default 0,
  likes bigint not null default 0,
  comments bigint not null default 0,
  duration text,
  category_id text,
  url text not null,
  embeddable boolean not null default true,
  live_broadcast_content text,
  topic text not null default 'All',
  format text not null default 'all',
  region text not null default 'WORLDWIDE',
  source text not null default 'youtube',
  verified_at timestamptz not null default now(),
  fetched_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  expires_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  topic_tags text[] not null default array['All']::text[],
  acquired_at timestamptz,
  stats_refreshed_at timestamptz,
  language text,
  language_confidence numeric,
  relevance_score numeric,
  relevance_confidence numeric
);

create index if not exists youtube_discovery_pool_cell_idx on public.youtube_discovery_pool (topic, region, published_at desc);
create index if not exists youtube_discovery_pool_channel_idx on public.youtube_discovery_pool (channel_id, published_at desc);

create table if not exists public.video_stats_snapshots (
  id bigint generated by default as identity primary key,
  video_id text not null,
  captured_at timestamptz not null default now(),
  views bigint not null default 0,
  likes bigint not null default 0,
  comments bigint not null default 0,
  unique (video_id, captured_at)
);
create index if not exists video_stats_snapshots_video_time_idx on public.video_stats_snapshots (video_id, captured_at desc);

create table if not exists public.discovery_pool_health (
  cell_key text primary key,
  topic text not null,
  format text not null,
  region text not null,
  language text not null default 'any',
  candidate_count integer not null default 0,
  signal_ready_count integer not null default 0,
  last_acquired_at timestamptz,
  last_stats_refresh_at timestamptz,
  last_error_at timestamptz,
  last_error text,
  updated_at timestamptz not null default now()
);

alter table public.youtube_discovery_pool enable row level security;
alter table public.video_stats_snapshots enable row level security;
alter table public.discovery_pool_health enable row level security;

drop policy if exists "Public can read verified discovery pool" on public.youtube_discovery_pool;
create policy "Public can read verified discovery pool" on public.youtube_discovery_pool for select to public using (verified_at <= now() and (expires_at is null or expires_at > now()));
