-- RALLIVIO Global Observation + Signal Intelligence Engine
-- Consolidated source-of-truth migration for adaptive observation, parallel-safe
-- leases, database-side signal computation, and global overview aggregates.

alter table public.youtube_discovery_pool
  add column if not exists next_observation_at timestamptz,
  add column if not exists observation_lease_until timestamptz,
  add column if not exists observation_worker text,
  add column if not exists observation_attempts integer not null default 0,
  add column if not exists last_observation_error text,
  add column if not exists signal_dirty_at timestamptz;

create index if not exists youtube_pool_observation_due_idx
  on public.youtube_discovery_pool (next_observation_at, observation_priority desc, last_observed_at)
  where tier <> 'archive';

create index if not exists youtube_pool_observation_lease_idx
  on public.youtube_discovery_pool (observation_lease_until)
  where observation_lease_until is not null;

create index if not exists video_stats_snapshots_video_captured_idx
  on public.video_stats_snapshots (video_id, captured_at desc);

create index if not exists discovery_signals_video_observed_idx
  on public.discovery_signals (video_id, observed_at desc);

create table if not exists public.discovery_signal_events (
  id bigint generated by default as identity primary key,
  video_id text not null,
  channel_id text,
  from_signal text,
  to_signal text not null,
  signal_labels jsonb not null default '[]'::jsonb,
  momentum_score numeric,
  evidence jsonb not null default '{}'::jsonb,
  observed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists discovery_signal_events_video_time_idx
  on public.discovery_signal_events (video_id, observed_at desc);

create index if not exists discovery_signal_events_time_idx
  on public.discovery_signal_events (created_at desc);

alter table public.discovery_signal_events enable row level security;

create or replace function public.enqueue_youtube_observation_job()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    new.next_observation_at := coalesce(new.next_observation_at, now());
  elsif tg_op = 'UPDATE' and (
    new.tier is distinct from old.tier
    or new.observation_priority is distinct from old.observation_priority
  ) then
    new.next_observation_at := least(coalesce(new.next_observation_at, now()), now());
  end if;
  return new;
end;
$$;

drop trigger if exists youtube_pool_observation_enqueue on public.youtube_discovery_pool;
create trigger youtube_pool_observation_enqueue
before insert or update of tier, observation_priority
on public.youtube_discovery_pool
for each row execute function public.enqueue_youtube_observation_job();

update public.youtube_discovery_pool
set next_observation_at = coalesce(next_observation_at, now())
where tier <> 'archive' and next_observation_at is null;

undefined

undefined

undefined

undefined

undefined

revoke all on function public.claim_youtube_observation_jobs(integer,text,integer) from public, anon, authenticated;
revoke all on function public.complete_youtube_observation_jobs(text[],timestamptz[],text) from public, anon, authenticated;
revoke all on function public.fail_youtube_observation_jobs(text[],text,text) from public, anon, authenticated;
revoke all on function public.recompute_discovery_signals() from public, anon, authenticated;
revoke all on function public.get_discovery_overview() from public, anon, authenticated;

grant execute on function public.claim_youtube_observation_jobs(integer,text,integer) to service_role;
grant execute on function public.complete_youtube_observation_jobs(text[],timestamptz[],text) to service_role;
grant execute on function public.fail_youtube_observation_jobs(text[],text,text) to service_role;
grant execute on function public.recompute_discovery_signals() to service_role;
grant execute on function public.get_discovery_overview() to service_role;
